[package]
name = "bunny-wl-pet"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = "0.31"
wayland-protocols = "0.32"
wayland-protocols-wlr = "0.3"
memmap2 = "0.9"
tempfile = "3"
image = "0.25"
